# Generated by Django 5.1.6 on 2025-03-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="paid_course",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="payment",
            old_name="paid_lesson",
            new_name="lesson",
        ),
    ]