# Generated by Django 5.1.6 on 2025-03-28 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_paid_course_payment_course_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Платеж", "verbose_name_plural": "Платежи"},
        ),
    ]