# Generated by Django 5.1.6 on 2025-03-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="name_course",
            new_name="course",
        ),
    ]