# Generated by Django 5.1.6 on 2025-03-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_subscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="Course",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="subscription",
            old_name="User",
            new_name="user",
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_subscribe",
            field=models.BooleanField(default=False, verbose_name="подписка"),
        ),
    ]